#!/usr/bin/sh

echo "To begin using NSCA, first edit /etc/nagios/nsca.cfg, update the"
echo "password and decryption_method lines. Then start the nsca service"
echo "by running the command 'svcadm enable nsca' as root."
